"""Generate MAP.md from the frontmatter of every tracked Markdown file.

  python tools/generate_map.py           write MAP.md from the working tree
  python tools/generate_map.py --check   write nothing; compare the staged
                                         MAP.md with what the staged files
                                         would produce

Exit codes, so a caller can tell the causes apart:

  0  the map is current, or was written
  1  a structural error: a file with no frontmatter or no description, a
     line the parser cannot read, or git failing. Fix the file.
  2  the map is stale or missing. Regenerate it and stage it.

A hook that read every non-zero exit as "stale" would announce a cause it
had not tested, so the two are kept apart.

The file list is the index (`git ls-files`), so a new file counts once it
is staged. --check reads each file's staged content, not the working tree,
because the gate must judge what is about to be committed; a working-tree
check would pass a commit whose staged content differs (Brief 2, gate C).

Coverage: every tracked .md except MAP.md itself and docs/design/DESIGN.md,
which is an upload for Claude Design and stays free of frontmatter.

Standard library only (scope floor line 14). Frontmatter is read line by
line rather than with a YAML library: `key: value`, blank lines and `#`
comment lines. Decision records carry commented lines such as
`# consulted:`, and those are skipped. Anything else fails loudly rather
than being guessed at.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MAP = "MAP.md"
EXCLUDED = {MAP, "docs/design/DESIGN.md"}
FRONTMATTER_RE = re.compile(r"\A---\r?\n(.*?)\r?\n---\r?\n", re.DOTALL)
KEY_RE = re.compile(r"^([A-Za-z][\w-]*):\s*(.*)$")

HEADER = """\
---
type: map
description: Every tracked Markdown file with its type, status and description, grouped by folder. Generated; never edit by hand.
status: generated
---

# Map

Generated by `tools/generate_map.py` from each file's frontmatter. Do not
edit this file; edit the file's frontmatter and run the generator. The
pre-commit hook refuses a commit that leaves it stale (ADR-0007).

Every tracked Markdown file is listed except this one and
`docs/design/DESIGN.md`, an upload for Claude Design that carries no
frontmatter. Decision records have no `type`; their `topic` is shown.
"""


class MapError(Exception):
    """A structural problem: exit 1."""


def git(*args: str) -> bytes:
    try:
        result = subprocess.run(["git", *args], cwd=ROOT, capture_output=True)
    except FileNotFoundError:
        raise MapError("missing tool: git is not on the PATH") from None
    if result.returncode != 0:
        raise MapError(f"git {' '.join(args)} failed: "
                       f"{result.stderr.decode('utf-8', 'replace').strip()}")
    return result.stdout


def tracked_markdown() -> list[str]:
    paths = git("ls-files", "-z", "--", "*.md").decode("utf-8").split("\0")
    return sorted(p for p in paths if p and p not in EXCLUDED)


def read(path: str, staged: bool) -> str:
    if staged:
        return git("cat-file", "blob", f":{path}").decode("utf-8")
    file = ROOT / path
    if not file.exists():
        raise MapError(f"{path} is in the index but not in the working tree; "
                       "stage its deletion or restore it")
    return file.read_text(encoding="utf-8")


def frontmatter(path: str, text: str) -> dict[str, str]:
    match = FRONTMATTER_RE.match(text)
    if not match:
        raise MapError(f"{path}: no frontmatter. Add a --- block with "
                       "type, description and status")
    fields = {}
    for number, line in enumerate(match[1].splitlines(), start=2):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        parsed = KEY_RE.match(stripped)
        if not parsed:
            raise MapError(f"{path}, line {number}: cannot read frontmatter line {line!r}")
        fields[parsed[1]] = parsed[2].strip().strip("'\"")
    if not fields.get("description"):
        raise MapError(f"{path}: frontmatter has no description")
    return fields


def cell(value: str) -> str:
    return value.replace("|", "\\|")


def render(staged: bool) -> str:
    groups: dict[str, list[str]] = {}
    problems = []
    for path in tracked_markdown():
        try:
            fields = frontmatter(path, read(path, staged))
        except MapError as error:
            problems.append(str(error))
            continue
        kind = fields.get("type") or (f"decision ({fields['topic']})" if "topic" in fields else "")
        folder = path.rpartition("/")[0] or "(root)"
        groups.setdefault(folder, []).append(
            f"| `{path}` | {cell(kind)} | {cell(fields.get('status', ''))} "
            f"| {cell(fields['description'])} |")
    if problems:
        raise MapError("\n".join(problems))

    parts = [HEADER]
    for folder in sorted(groups, key=lambda f: (f != "(root)", f)):
        parts.append(f"\n## {folder}\n\n| File | Type | Status | Description |\n|---|---|---|---|\n")
        parts.append("\n".join(groups[folder]) + "\n")
    return "".join(parts)


def main(argv: list[str]) -> int:
    check = argv == ["--check"]
    if argv and not check:
        print("usage: generate_map.py [--check]", file=sys.stderr)
        return 1
    try:
        expected = render(staged=check)
        if check:
            try:
                current = git("cat-file", "blob", f":{MAP}").decode("utf-8")
            except MapError:
                print(f"{MAP} is not staged. Run: python tools/generate_map.py, "
                      f"then git add {MAP}", file=sys.stderr)
                return 2
            if current != expected:
                print(f"{MAP} is stale against the staged files. Run: "
                      f"python tools/generate_map.py, then git add {MAP}", file=sys.stderr)
                return 2
            return 0
        (ROOT / MAP).write_text(expected, encoding="utf-8", newline="\n")
        print(f"wrote {MAP}: {sum(1 for line in expected.splitlines() if line.startswith('| `'))} files")
        return 0
    except MapError as error:
        print(f"map error:\n{error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
